#!/bin/bash

# skip if build is triggered by pull request
if [ $TRAVIS_PULL_REQUEST != "false" ]; then
  echo "this is PR, exiting"
  exit 0
fi

# enable error reporting to the console
set -e

# cleanup "_site"
rm -rf _site
mkdir _site

# clone remote repo to "_site"
echo "Clonning gh-pages"
git clone https://${GH_TOKEN}@github.com/stargate/website.git --branch gh-pages _site

# build with Jekyll into "_site"
echo "Pushing posts to algolia"
bundle exec jekyll algolia

echo "Running Jekyll Build"
bundle exec jekyll build

# push
echo "Pushing _site to gh-pages"
cd _site
git add --all
git commit -m "Travis #$TRAVIS_BUILD_NUMBER"
git push --force origin gh-pages

# Going back to the root folder
cd ..

# pushing docs to algolia
echo "Pushing docs to algolia"
docker run -it -e "APPLICATION_ID=$(echo $APPLICATION_ID)" -e "API_KEY=$(echo $API_KEY)" -e "CONFIG=$(cat config.json | jq -r tostring)" algolia/docsearch-scraper

echo "Done"
